using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

namespace SzafaKitEditor.Oracle {
    public class OracleWindow : EditorWindow {
        [SerializeField]
        private VisualTreeAsset m_VisualTreeAsset = default;

        [MenuItem("Szafa/Oracle")]
        public static void ShowWindow() {
            OracleWindow wnd = GetWindow<OracleWindow>();
            wnd.titleContent = new GUIContent("OracleWindow");
        }

        public void CreateGUI() {
            VisualElement root = rootVisualElement;

            VisualElement labelFromUXML = m_VisualTreeAsset.Instantiate();
            root.Add(labelFromUXML);
        }
    }
}